// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5tNVisqQ9-R56e3nI4rj0QNnXy3eV8fg',
    appId: '1:668530911988:web:c37ecde429ccefdea10ca1',
    messagingSenderId: '668530911988',
    projectId: 'tarea8-ba942',
    authDomain: 'tarea8-ba942.firebaseapp.com',
    storageBucket: 'tarea8-ba942.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv1etku9m-6o4LjTD65qg50dLL0NgsSJY',
    appId: '1:668530911988:android:f9f629426c3f8457a10ca1',
    messagingSenderId: '668530911988',
    projectId: 'tarea8-ba942',
    storageBucket: 'tarea8-ba942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8OiWc_Ucv2ZVvi0QWPv0nWmvmTxZ3ec4',
    appId: '1:668530911988:ios:0491c4fd289cc2c5a10ca1',
    messagingSenderId: '668530911988',
    projectId: 'tarea8-ba942',
    storageBucket: 'tarea8-ba942.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8OiWc_Ucv2ZVvi0QWPv0nWmvmTxZ3ec4',
    appId: '1:668530911988:ios:0491c4fd289cc2c5a10ca1',
    messagingSenderId: '668530911988',
    projectId: 'tarea8-ba942',
    storageBucket: 'tarea8-ba942.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5tNVisqQ9-R56e3nI4rj0QNnXy3eV8fg',
    appId: '1:668530911988:web:56e11cac56b6da97a10ca1',
    messagingSenderId: '668530911988',
    projectId: 'tarea8-ba942',
    authDomain: 'tarea8-ba942.firebaseapp.com',
    storageBucket: 'tarea8-ba942.appspot.com',
  );
}
